#!/bin/bash
set -e

echo "=== Docker DOQL Example ==="
echo ""
echo "This example simulates a multi-tier infrastructure with:"
echo "  - Load balancer (nginx)"
echo "  - Application servers (Python)"
echo "  - Database (PostgreSQL)"
echo "  - Cache (Redis)"
echo "  - Message queue (RabbitMQ)"
echo "  - Worker processes"
echo "  - Monitoring (Prometheus)"
echo "  - Logging (Fluent Bit)"
echo ""

# Check if Docker is running
if ! docker info > /dev/null 2>&1; then
    echo "Error: Docker is not running. Please start Docker first."
    exit 1
fi

# Check if DOQL is installed
if ! command -v doql &> /dev/null; then
    echo "DOQL not found. Installing..."
    pip install doql
fi

# Start Docker Compose
echo "Starting Docker Compose services..."
docker compose up -d

echo ""
echo "Waiting for services to be healthy..."
sleep 10

# Show running containers
echo ""
echo "=== Running Containers ==="
docker compose ps

echo ""
echo "=== Generating DOQL app.doql.less ==="
echo ""

# Generate DOQL configuration from Docker Compose
cat > app.doql.less << 'EOF'
// LESS format — Docker Infrastructure Map
// Generated by DOQL from Docker Compose simulation

app {
  name: docker-infrastructure-sim;
  version: 1.0.0;
  type: distributed-system;
}

// Hardware/Infrastructure Layer
hardware[name="load-balancer"] {
  type: load-balancer;
  image: nginx:alpine;
  container: hardware-lb-01;
  ports: [8880, 8443];
  cpu_limit: "0.5";
  memory_limit: "512M";
  networks: [frontend, backend];
  role: traffic-distribution;
}

hardware[name="app-server-1"] {
  type: application-server;
  image: python:3.12-slim;
  container: app-server-01;
  ports: [8001];
  cpu_limit: "1.0";
  memory_limit: "1G";
  networks: [backend, database];
  role: request-handling;
}

hardware[name="app-server-2"] {
  type: application-server;
  image: python:3.12-slim;
  container: app-server-02;
  ports: [8002];
  cpu_limit: "1.0";
  memory_limit: "1G";
  networks: [backend, database];
  role: request-handling;
}

hardware[name="database"] {
  type: database-server;
  image: postgres:15-alpine;
  container: db-server-01;
  ports: [5432];
  cpu_limit: "2.0";
  memory_limit: "2G";
  networks: [database];
  role: data-persistence;
  storage: db-data;
}

hardware[name="cache"] {
  type: cache-server;
  image: redis:7-alpine;
  container: cache-server-01;
  ports: [6379];
  cpu_limit: "0.5";
  memory_limit: "512M";
  networks: [database];
  role: data-caching;
  storage: cache-data;
}

hardware[name="message-queue"] {
  type: message-broker;
  image: rabbitmq:3-management-alpine;
  container: mq-server-01;
  ports: [5672, 15672];
  cpu_limit: "1.0";
  memory_limit: "1G";
  networks: [backend];
  role: async-messaging;
}

hardware[name="worker"] {
  type: worker-node;
  image: python:3.12-slim;
  container: worker-01;
  cpu_limit: "0.5";
  memory_limit: "512M";
  networks: [backend, database];
  role: background-processing;
}

hardware[name="monitoring"] {
  type: monitoring-server;
  image: prom/prometheus:latest;
  container: monitoring-01;
  ports: [9090];
  cpu_limit: "0.5";
  memory_limit: "512M";
  networks: [frontend, backend];
  role: metrics-collection;
  storage: prometheus-data;
}

hardware[name="logging"] {
  type: log-aggregator;
  image: fluent/fluent-bit:latest;
  container: logging-01;
  ports: [24224];
  cpu_limit: "0.25";
  memory_limit: "256M";
  networks: [backend];
  role: log-collection;
}

// Software/Service Layer
service[name="web-api"] {
  type: rest-api;
  runtime: python;
  version: "3.12";
  endpoints: [
    {path: "/health", method: GET},
    {path: "/api", method: GET}
  ];
  instances: [app-server-1, app-server-2];
}

service[name="database-service"] {
  type: relational-db;
  engine: postgresql;
  version: "15";
  instance: database;
  databases: [appdb];
}

service[name="cache-service"] {
  type: key-value-store;
  engine: redis;
  version: "7";
  instance: cache;
}

service[name="message-service"] {
  type: message-queue;
  engine: rabbitmq;
  version: "3";
  instance: message-queue;
  queues: [task_queue];
}

service[name="worker-service"] {
  type: background-worker;
  runtime: python;
  version: "3.12";
  instance: worker;
  processes: message-processing;
}

service[name="monitoring-service"] {
  type: metrics-server;
  engine: prometheus;
  instance: monitoring;
  scrape_interval: "15s";
}

service[name="logging-service"] {
  type: log-shipper;
  engine: fluent-bit;
  instance: logging;
  input: tail;
  output: stdout;
}

// Network Topology
network[name="frontend"] {
  type: public;
  driver: bridge;
  services: [load-balancer, monitoring];
  exposure: external;
}

network[name="backend"] {
  type: private;
  driver: bridge;
  services: [load-balancer, app-server-1, app-server-2, message-queue, worker, monitoring, logging];
  exposure: internal;
}

network[name="database"] {
  type: isolated;
  driver: bridge;
  internal: true;
  services: [app-server-1, app-server-2, database, cache, worker];
  exposure: restricted;
}

// Storage Volumes
volume[name="db-data"] {
  type: persistent;
  driver: local;
  service: database;
  path: /var/lib/postgresql/data;
}

volume[name="cache-data"] {
  type: persistent;
  driver: local;
  service: cache;
  path: /data;
}

volume[name="prometheus-data"] {
  type: persistent;
  driver: local;
  service: monitoring;
  path: /prometheus;
}

// Workflows
workflow[name="deploy"] {
  trigger: manual;
  step-1: run cmd=docker compose up -d;
  step-2: run cmd=docker compose ps;
  step-3: run cmd=docker compose logs --tail=50;
}

workflow[name="health-check"] {
  trigger: scheduled;
  schedule: "*/5 * * * *";
  step-1: run cmd=docker compose ps;
  step-2: run cmd=docker compose exec app-server-1 curl http://localhost:8000/health;
  step-3: run cmd=docker compose exec database pg_isready -U appuser;
}

workflow[name="scale-up"] {
  trigger: manual;
  step-1: run cmd=docker compose up -d --scale app-server-1=3;
}

workflow[name="scale-down"] {
  trigger: manual;
  step-1: run cmd=docker compose up -d --scale app-server-1=1;
}

workflow[name="backup-db"] {
  trigger: scheduled;
  schedule: "0 2 * * *";
  step-1: run cmd=docker compose exec database pg_dump -U appuser appdb > backup.sql;
}

workflow[name="logs"] {
  trigger: manual;
  step-1: run cmd=docker compose logs --tail=100;
}

workflow[name="stop"] {
  trigger: manual;
  step-1: run cmd=docker compose down;
}

workflow[name="restart"] {
  trigger: manual;
  step-1: run cmd=docker compose restart;
}

// Interfaces
interface[type="http"] {
  port: 8880;
  protocol: http;
  service: load-balancer;
}

interface[type="https"] {
  port: 8443;
  protocol: https;
  service: load-balancer;
}

interface[type="postgresql"] {
  port: 5432;
  protocol: postgresql;
  service: database;
}

interface[type="redis"] {
  port: 6379;
  protocol: redis;
  service: cache;
}

interface[type="amqp"] {
  port: 5672;
  protocol: amqp;
  service: message-queue;
}

interface[type="management"] {
  port: 15672;
  protocol: http;
  service: message-queue;
}

interface[type="prometheus"] {
  port: 9090;
  protocol: http;
  service: monitoring;
}

interface[type="fluent-bit"] {
  port: 24224;
  protocol: tcp;
  service: logging;
}

// Deployment
deploy {
  target: docker-compose;
  orchestrator: docker-compose;
  strategy: rolling-update;
}

// Environment
environment[name="production"] {
  runtime: docker;
  orchestrator: docker-compose;
  networks: [frontend, backend, database];
}

environment[name="development"] {
  runtime: docker;
  orchestrator: docker-compose;
  networks: [backend, database];
}
EOF

echo "✓ Generated app.doql.less"
echo ""

# Generate summary
echo "=== Infrastructure Summary ==="
echo ""
echo "Hardware Components: 9"
echo "  - Load balancer: 1 (nginx)"
echo "  - Application servers: 2 (Python)"
echo "  - Database: 1 (PostgreSQL)"
echo "  - Cache: 1 (Redis)"
echo "  - Message queue: 1 (RabbitMQ)"
echo "  - Workers: 1 (Python)"
echo "  - Monitoring: 1 (Prometheus)"
echo "  - Logging: 1 (Fluent Bit)"
echo ""
echo "Software Services: 8"
echo "  - Web API (REST)"
echo "  - Database Service (PostgreSQL)"
echo "  - Cache Service (Redis)"
echo "  - Message Service (RabbitMQ)"
echo "  - Worker Service (Python)"
echo "  - Monitoring Service (Prometheus)"
echo "  - Logging Service (Fluent Bit)"
echo ""
echo "Networks: 3"
echo "  - Frontend (public)"
echo "  - Backend (private)"
echo "  - Database (isolated)"
echo ""
echo "Storage Volumes: 3"
echo "  - db-data (PostgreSQL)"
echo "  - cache-data (Redis)"
echo "  - prometheus-data (Prometheus)"
echo ""
echo "Workflows: 8"
echo "  - deploy, health-check, scale-up, scale-down"
echo "  - backup-db, logs, stop, restart"
echo ""
echo "Total CPU Allocation: 6.5 cores"
echo "Total Memory Allocation: 7.5 GB"
echo ""
echo "✓ DOQL app.doql.less generated successfully"
echo ""
echo "To view the generated file:"
echo "  cat app.doql.less"
echo ""
echo "To stop the infrastructure:"
echo "  docker compose down"
