"""Source path classification and default noise filtering.

The analyzer intentionally tracks some non-code files so export caches are
invalidated when project manifests or docs change. Those files should not be
treated the same as production source, and generated code2llm artefacts should
not be fed back into the next analysis run.
"""

from __future__ import annotations

from pathlib import Path
from typing import Optional


CODE_EXTENSIONS = {
    ".py", ".ts", ".tsx", ".js", ".jsx", ".mjs", ".cjs", ".go", ".rs",
    ".java", ".cpp", ".cc", ".cxx", ".hpp", ".hh", ".h", ".c", ".cs",
    ".rb", ".rbw", ".php", ".swift", ".kt", ".kts", ".scala", ".r",
    ".m", ".sh", ".bash", ".zsh", ".dart", ".ex", ".exs", ".clj",
    ".cljs", ".hs", ".lua", ".pl", ".pm", ".raku", ".rakumod",
}

DOC_EXTENSIONS = {".md", ".mdx", ".markdown", ".rst", ".adoc", ".asciidoc", ".txt"}

STRUCTURAL_ONLY_EXTENSIONS = {
    ".yaml", ".yml", ".toml", ".ini", ".cfg", ".conf", ".properties",
    ".xml", ".json", ".json5", ".jsonc", ".env", ".proto", ".graphql",
    ".gql", ".avsc", ".prisma", ".tf", ".tfvars", ".hcl", ".bicep",
    ".nix",
    *DOC_EXTENSIONS,
}

ARCHIVE_DIR_NAMES = frozenset({
    "_archive", "archive", "archives", "_archives", "legacy", "old",
})

GENERATED_OUTPUT_DIR_NAMES = frozenset({
    ".code2llm_cache",
    "code2llm_output",
    "output_toon",
    "output_all",
    "output_comparison",
    "output_modes",
    "analysis_all",
    "compare",
    "calls_output",
    "refactor_output",
    "playwright-report",
    "test-results",
    "html-report",
})

GENERATED_EXACT_FILENAMES = frozenset({
    "analysis.toon",
    "analysis.toon.yaml",
    "analysis_toon.yaml",
    ".code2llm_incremental.json",
    "map.toon",
    "map.toon.yaml",
    "evolution.toon",
    "evolution.toon.yaml",
    "validation.toon.yaml",
    "duplication.toon.yaml",
    "calls.toon.yaml",
    "calls.yaml",
    "calls.mmd",
    "compact_flow.mmd",
    "flow.mmd",
    "flow_detailed.mmd",
    "flow_full.mmd",
    "mermaid.export",
    "project.toon",
    "project.toon.yaml",
    "project.toon.txt",
    "defscan-classes-py.md",
    "defscan-classes-ts.md",
    "sumd.md",
    "sumr.md",
})

GENERATED_PREFIXES = ("defscan-",)

GENERATED_SNIFF_FILENAMES = frozenset({
    "context.md",
    "readme.md",
    "index.html",
    "prompt.txt",
})

GENERATED_MARKERS = (
    "generated by: `code2llm`",
    "generated by code2llm",
    "code2llm - generated analysis files",
    "<title>code2llm analysis results</title>",
    "# system architecture analysis\n<!-- generated",
    "use the attached/generated files as the authoritative context.",
)


def _relative_parts(path: Path, project_root: Optional[Path]) -> tuple[str, ...]:
    """Return normalized relative path parts for classification."""
    try:
        if project_root:
            rel = path.resolve().relative_to(project_root.resolve())
        else:
            rel = path
    except (OSError, ValueError, RuntimeError):
        rel = path
    return tuple(part.lower() for part in rel.parts)


def _looks_like_generated_content(path: Path) -> bool:
    """Cheap content sniff for generic generated filenames such as README.md."""
    try:
        text = path.read_text(encoding="utf-8", errors="ignore")[:4096].lower()
    except (OSError, UnicodeDecodeError):
        return False
    return any(marker in text for marker in GENERATED_MARKERS)


def _has_code2llm_output_manifest(path: Path) -> bool:
    """Return True if a directory looks like a code2llm output folder."""
    return (
        (path / "analysis.toon.yaml").exists()
        or (path / "analysis.toon").exists()
        or (path / "map.toon.yaml").exists()
    )


def is_generated_artifact(path: str | Path, project_root: Optional[Path] = None) -> bool:
    """Return True when *path* is a generated analysis/report artefact."""
    p = Path(path)
    parts = _relative_parts(p, project_root)
    if any(part in GENERATED_OUTPUT_DIR_NAMES for part in parts[:-1]):
        return True

    if project_root:
        rel_parts = parts[:-1]
        for idx, part in enumerate(rel_parts):
            if part != "project":
                continue
            candidate = Path(project_root).joinpath(*parts[: idx + 1])
            if _has_code2llm_output_manifest(candidate):
                return True

    name = p.name.lower()
    if name in GENERATED_EXACT_FILENAMES:
        return True
    if any(name.startswith(prefix) for prefix in GENERATED_PREFIXES):
        return True
    if name in GENERATED_SNIFF_FILENAMES and _looks_like_generated_content(p):
        return True

    # The default code2llm output folder is commonly named "project". Avoid
    # treating arbitrary project/ directories as generated unless the filename
    # itself is a known code2llm artefact.
    if "project" in parts[:-1] and name in GENERATED_EXACT_FILENAMES:
        return True

    return False


def classify_source_path(path: str | Path, project_root: Optional[Path] = None) -> str:
    """Classify a path for reporting and filtering."""
    p = Path(path)
    parts = _relative_parts(p, project_root)
    if is_generated_artifact(p, project_root):
        return "generated"
    if any(part in ARCHIVE_DIR_NAMES for part in parts[:-1]):
        return "archive"
    if any(part in {"tests", "test", "testing", "__tests__"} for part in parts[:-1]):
        return "test"
    ext = p.suffix.lower()
    if ext in DOC_EXTENSIONS:
        return "docs"
    if ext in STRUCTURAL_ONLY_EXTENSIONS:
        return "config"
    if ext in CODE_EXTENSIONS:
        return "source"
    return "other"


def is_structural_only_file(path: str | Path) -> bool:
    """Return True for tracked non-code text files that should emit no symbols."""
    return Path(path).suffix.lower() in STRUCTURAL_ONLY_EXTENSIONS
