"""
README Exporter for code2llm

Generates comprehensive README.md documentation for analysis output files.
"""

import os
from datetime import datetime
from pathlib import Path
from typing import Dict, Any

from .base import Exporter as BaseExporter


class READMEExporter(BaseExporter):
    """Export README.md with documentation of all generated files."""
    
    def export(self, analysis_result: Any, output_path: str) -> None:
        """Generate README.md documentation."""
        output_dir = Path(output_path).parent
        project_path = analysis_result.project_path if hasattr(analysis_result, 'project_path') else './'
        
        # Collect statistics
        total_functions = len(analysis_result.functions) if hasattr(analysis_result, 'functions') else 0
        total_classes = len(analysis_result.classes) if hasattr(analysis_result, 'classes') else 0
        total_modules = len(analysis_result.modules) if hasattr(analysis_result, 'modules') else 0
        
        # Read existing files to extract insights
        insights = self._extract_insights(output_dir, analysis_result)
        
        readme_content = self._generate_readme_content(
            project_path=project_path,
            output_dir=output_dir,
            total_functions=total_functions,
            total_classes=total_classes,
            total_modules=total_modules,
            insights=insights
        )
        
        with open(output_path, 'w', encoding='utf-8') as f:
            f.write(readme_content)
    
    def _extract_insights(self, output_dir: Path, analysis_result: Any) -> Dict[str, Any]:
        """Extract insights from existing analysis files."""
        insights = {
            'critical_functions': 0,
            'god_modules': 0,
            'refactoring_actions': 0,
            'has_health_issues': False,
            'has_evolution_plan': False
        }
        
        # Check analysis.toon for health metrics
        analysis_toon = output_dir / 'analysis.toon'
        if analysis_toon.exists():
            try:
                content = analysis_toon.read_text(encoding='utf-8')
                # Extract critical functions count
                for line in content.split('\n'):
                    if 'critical:' in line:
                        # Format: critical:57/537
                        parts = line.split('critical:')[1].split('/')[0]
                        insights['critical_functions'] = int(parts.strip())
                    elif 'GOD' in line and '🔴' in line:
                        insights['god_modules'] += 1
                    elif line.strip().startswith('🔴'):
                        insights['has_health_issues'] = True
            except Exception:
                pass
        
        # Check evolution.toon for refactoring plan
        evolution_toon = output_dir / 'evolution.toon'
        if evolution_toon.exists():
            try:
                content = evolution_toon.read_text(encoding='utf-8')
                if 'REFACTOR[' in content:
                    # Count refactoring actions
                    for line in content.split('\n'):
                        if line.strip().startswith(('1.', '2.', '3.', '4.', '5.', '6.', '7.', '8.', '9.')):
                            insights['refactoring_actions'] += 1
                    insights['has_evolution_plan'] = True
            except Exception:
                pass
        
        return insights
    
    def _generate_readme_content(self, project_path: str, output_dir: Path, 
                                total_functions: int, total_classes: int, total_modules: int,
                                insights: Dict[str, Any]) -> str:
        """Generate the complete README.md content."""
        
        current_date = datetime.now().strftime('%Y-%m-%d')
        
        content = f"""# code2llm - Generated Analysis Files

This directory contains the complete analysis of your Python project generated by `code2llm`. Each file serves a specific purpose for understanding, refactoring, and documenting your codebase.

## 📁 Generated Files Overview

When you run `code2llm ./ -f all`, the following files are created:

### 🎯 Core Analysis Files

| File | Format | Purpose | Key Insights |
|------|--------|---------|--------------|
| `analysis.toon` | **TOON** | **🔥 Health diagnostics** - Complexity, god modules, coupling | {insights['critical_functions']} critical functions, {insights['god_modules']} god modules |
| `evolution.toon` | **TOON** | **📋 Refactoring queue** - Prioritized improvements | {insights['refactoring_actions']} refactoring actions needed |
| `flow.toon` | **TOON** | **🔄 Data flow analysis** - Pipelines, contracts, types | Data dependencies and side effects |
| `map.toon` | **TOON** | **🗺️ Structural map** - Modules, imports, signatures | Project architecture overview |

### 🤖 LLM-Ready Documentation

| File | Format | Purpose | Use Case |
|------|--------|---------|----------|
| `context.md` | **Markdown** | **📖 LLM narrative** - Architecture summary | Paste into ChatGPT/Claude for code analysis |
| `analysis.yaml` | **YAML** | **📊 Structured data** - Machine-readable | For scripts and automated processing |
| `analysis.json` | **JSON** | **🔧 API format** - Programmatic access | For integration with other tools |

### 📊 Visualizations

| File | Format | Purpose | Description |
|------|--------|---------|-------------|
| `flow.mmd` | **Mermaid** | **🔄 Control flow diagram** | Function call paths with complexity styling |
| `calls.mmd` | **Mermaid** | **📞 Call graph** | Function dependencies (edges only) |
| `compact_flow.mmd` | **Mermaid** | **📦 Module overview** | Aggregated module-level view |
| `*.png` | **PNG** | **🖼️ Visual diagrams** | Rendered versions of Mermaid files |

## 🚀 Quick Start Commands

### Basic Analysis
```bash
# Quick health check (TOON format only)
code2llm ./ -f toon

# Generate all formats (what created these files)
code2llm ./ -f all

# LLM-ready context only
code2llm ./ -f context
```

### Performance Options
```bash
# Fast analysis for large projects
code2llm ./ -f toon --strategy quick

# Memory-limited analysis
code2llm ./ -f all --max-memory 500

# Skip PNG generation (faster)
code2llm ./ -f all --no-png
```

### Refactoring Focus
```bash
# Get refactoring recommendations
code2llm ./ -f evolution

# Focus on specific code smells
code2llm ./ -f toon --refactor --smell god_function

# Data flow analysis
code2llm ./ -f flow --data-flow
```

## 📖 Understanding Each File

### `analysis.toon` - Health Diagnostics
**Purpose**: Quick overview of code health issues
**Key sections**:
- **HEALTH**: Critical issues (🔴) and warnings (🟡)
- **REFACTOR**: Prioritized refactoring actions
- **COUPLING**: Module dependencies and potential cycles
- **LAYERS**: Package complexity metrics
- **FUNCTIONS**: High-complexity functions (CC ≥ 10)
- **CLASSES**: Complex classes needing attention

**Example usage**:
```bash
# View health issues
cat analysis.toon | head -30

# Check refactoring priorities
grep "REFACTOR" analysis.toon
```

### `evolution.toon` - Refactoring Queue
**Purpose**: Step-by-step refactoring plan
**Key sections**:
- **NEXT**: Immediate actions to take
- **RISKS**: Potential breaking changes
- **METRICS-TARGET**: Success criteria

**Example usage**:
```bash
# Get refactoring plan
cat evolution.toon

# Track progress
grep "NEXT" evolution.toon
```

### `flow.toon` - Data Flow Analysis
**Purpose**: Understand data movement through the system
**Key sections**:
- **PIPELINES**: Data processing chains
- **CONTRACTS**: Function input/output contracts
- **SIDE_EFFECTS**: Functions with external impacts

**Example usage**:
```bash
# Find data pipelines
grep "PIPELINES" flow.toon

# Identify side effects
grep "SIDE_EFFECTS" flow.toon
```

### `map.toon` - Structural Map
**Purpose**: High-level architecture overview
**Key sections**:
- **MODULES**: All modules with basic stats
- **IMPORTS**: Dependency relationships
- **SIGNATURES**: Public API functions

**Example usage**:
```bash
# See project structure
cat map.toon | head -50

# Find public APIs
grep "SIGNATURES" map.toon
```

### `context.md` - LLM Narrative
**Purpose**: Ready-to-paste context for AI assistants
**Key sections**:
- **Overview**: Project statistics
- **Architecture**: Module breakdown
- **Entry Points**: Public interfaces
- **Patterns**: Design patterns detected

**Example usage**:
```bash
# Copy to clipboard for LLM
cat context.md | pbcopy  # macOS
cat context.md | xclip -sel clip  # Linux

# Use with Claude/ChatGPT for code analysis
```

### Visualization Files (`*.mmd`, `*.png`)
**Purpose**: Visual understanding of code structure
**Files**:
- `flow.mmd` - Detailed control flow with complexity colors
- `calls.mmd` - Simple call graph
- `compact_flow.mmd` - High-level module view
- `*.png` - Pre-rendered images

**Example usage**:
```bash
# View diagrams
open flow.png  # macOS
xdg-open flow.png  # Linux

# Edit in Mermaid Live Editor
# Copy content of .mmd files to https://mermaid.live
```

## 🔍 Common Analysis Patterns

### 1. Code Health Assessment
```bash
# Quick health check
code2llm ./ -f toon
cat analysis.toon | grep -E "(HEALTH|REFACTOR)"
```

### 2. Refactoring Planning
```bash
# Get refactoring queue
code2llm ./ -f evolution
cat evolution.toon

# Focus on specific issues
code2llm ./ -f toon --refactor --smell god_function
```

### 3. LLM Assistance
```bash
# Generate context for AI
code2llm ./ -f context
cat context.md

# Use with Claude: "Based on this context, help me refactor the god modules"
```

### 4. Team Documentation
```bash
# Generate all docs for team
code2llm ./ -f all -o ./docs/

# Create visual diagrams
open docs/flow.png
```

## 📊 Interpreting Metrics

### Complexity Metrics (CC)
- **🔴 Critical (≥5.0)**: Immediate refactoring needed
- **🟠 High (3.0-4.9)**: Consider refactoring
- **🟡 Medium (1.5-2.9)**: Monitor complexity
- **🟢 Low (0.1-1.4)**: Acceptable
- **⚪ Basic (0.0)**: Simple functions

### Module Health
- **GOD Module**: Too large (>500 lines, >20 methods)
- **HUB**: High fan-out (calls many modules)
- **FAN-IN**: High incoming dependencies
- **CYCLES**: Circular dependencies

### Data Flow Indicators
- **PIPELINE**: Sequential data processing
- **CONTRACT**: Clear input/output specification
- **SIDE_EFFECT**: External state modification

## 🛠️ Integration Examples

### CI/CD Pipeline
```bash
#!/bin/bash
# Analyze code quality in CI
code2llm ./ -f toon -o ./analysis
if grep -q "🔴 GOD" ./analysis/analysis.toon; then
    echo "❌ God modules detected"
    exit 1
fi
```

### Pre-commit Hook
```bash
#!/bin/sh
# .git/hooks/pre-commit
code2llm ./ -f toon -o ./temp_analysis
if grep -q "🔴" ./temp_analysis/analysis.toon; then
    echo "⚠️  Critical issues found. Review before committing."
fi
rm -rf ./temp_analysis
```

### Documentation Generation
```bash
# Generate docs for README
code2llm ./ -f context -o ./docs/
echo "## Architecture" >> README.md
cat docs/context.md >> README.md
```

## 📚 Next Steps

1. **Review `analysis.toon`** - Identify critical issues
2. **Check `evolution.toon`** - Plan refactoring priorities
3. **Use `context.md`** - Get LLM assistance for complex changes
4. **Reference visualizations** - Understand system architecture
5. **Track progress** - Re-run analysis after changes

## 🔧 Advanced Usage

### Custom Analysis
```bash
# Deep analysis with all insights
code2llm ./ -m hybrid -f all --max-depth 15 -v

# Performance-optimized
code2llm ./ -m static -f toon --strategy quick

# Refactoring-focused
code2llm ./ -f toon,evolution --refactor
```

### Output Customization
```bash
# Separate output directories
code2llm ./ -f all -o ./analysis-$(date +%Y%m%d)

# Split YAML into multiple files
code2llm ./ -f yaml --split-output

# Separate orphaned functions
code2llm ./ -f yaml --separate-orphans
```

---

**Generated by**: `code2llm ./ -f all --readme`  
**Analysis Date**: {current_date}  
**Total Functions**: {total_functions}  
**Total Classes**: {total_classes}  
**Modules**: {total_modules}  

For more information about code2llm, visit: https://github.com/tom-sapletta/code2llm
"""
        
        return content
